Document: wilton
Title: Debian wilton Manual
Author: Wilton Runtime
Abstract: This manual describes what wilton is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wilton/wilton.sgml.gz

Format: postscript
Files: /usr/share/doc/wilton/wilton.ps.gz

Format: text
Files: /usr/share/doc/wilton/wilton.text.gz

Format: HTML
Index: /usr/share/doc/wilton/html/index.html
Files: /usr/share/doc/wilton/html/*.html
