#!/bin/bash
#
# Copyright 2020, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

export BUILDER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
export WILTON_DIR="$BUILDER_DIR"../../

if [ -z "$JAVA_HOME" ] ; then
    echo "'JAVA_HOME' environment variable must be defined"
    exit 1
fi

if [ -z "$1" ] ; then
    echo "USAGE: builder <task> [args]"
    exit 1
fi

"$JAVA_HOME"/bin/java \
        -XX:MaxRAM=256M \
        -XX:+UseSerialGC \
        -XX:+TieredCompilation \
        -XX:TieredStopAtLevel=1 \
        -cp "$WILTON_DIR"tools/mvnrepo/org/mozilla/rhino/1.7.7.1/rhino-1.7.7.1.jar \
        org.mozilla.javascript.tools.shell.Main \
        -O -1 \
        "$BUILDER_DIR"init/runTask.js \
        "$*"

